import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, CloudSun, Database, Droplets, Sprout } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { ErrorCard, LoadingCard, WorkflowLayout } from "../../components/farmer/WorkflowLayout";
import { ensureAssessment, type WorkflowData } from "../../lib/decision-workflow";

const stage = { vegetative: "Vegetatif", flowering: "Berbunga", ripening: "Pematangan", unknown: "Belum diketahui" };
const value=(v:unknown)=>v==null||v===""?"Belum tersedia":String(v);
export function ConditionSummaryPage(){const{landId=""}=useParams();const[data,setData]=useState<WorkflowData>();const[error,setError]=useState("");useEffect(()=>{if(landId)ensureAssessment(landId).then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:"Assessment gagal dimuat"));},[landId]);return <WorkflowLayout landId={landId} step="3 · Ringkasan" title="Ringkasan kondisi lahan" subtitle="Sintesis ini berasal dari ruleset, Field Pulse, konteks tanaman, dan bukti BMKG yang benar-benar tersimpan.">{error?<ErrorCard message={error}/>:!data?<LoadingCard/>:<><section className="rounded-2xl bg-[#213014] p-6 text-white"><p className="text-xs font-bold text-[#98cf6a]">{data.land.name} · {stage[data.crop.growth_stage]}</p><h2 className="mt-3 font-display text-2xl font-bold">{data.result.assessment.summary}</h2><p className="mt-3 text-sm text-[#d9e7cb]">Kekuatan dasar: {value(data.result.assessment.basis_strength)} · Ruleset: {value(data.result.assessment.rule_version)}</p></section><div className="mt-5 grid gap-5 md:grid-cols-2"><Card icon={<Sprout/>} title="Faktor yang digunakan" items={data.result.assessment.factors}/><Card icon={<Database/>} title="Data yang belum tersedia" items={data.result.assessment.missing_evidence}/><Card icon={<Droplets/>} title="Keterbatasan" items={data.result.assessment.limitations}/><section className="rounded-2xl bg-white p-5"><h3 className="flex items-center gap-2 font-bold"><CloudSun size={19}/>Bukti tertaut ({data.evidence.length})</h3><div className="mt-4 space-y-3">{data.evidence.map(e=><div key={e.id} className="rounded-xl bg-[#f3f3ec] p-3 text-sm"><b>{e.type==="bmkg_forecast"?"Prakiraan BMKG":e.type==="field_pulse"?"Field Pulse":e.type}</b><p className="mt-1 text-xs text-[#56652e]">{e.source||"Sumber tidak dicatat"} · {e.freshness_status||"kesegaran belum dinilai"} · {e.is_mock?"demo/mock":"non-mock"}</p></div>)}</div></section></div><div className="mt-6 flex justify-end"><Link to={`/farmer/lands/${landId}/action-alternatives`} className="flex items-center gap-2 rounded-xl bg-[#85c254] px-5 py-3 text-sm font-bold">Lihat opsi dari ruleset <ArrowRight size={16}/></Link></div></>}</WorkflowLayout>}
function Card({icon,title,items}:{icon:ReactNode;title:string;items?:string[]}){return <section className="rounded-2xl bg-white p-5"><h3 className="flex items-center gap-2 font-bold">{icon}{title}</h3>{items?.length?<ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-[#44483f]">{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p className="mt-4 text-sm text-[#666a60]">Tidak ada yang dicatat oleh assessment.</p>}</section>}
