import { useEffect, useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { ArrowLeft, CloudSun, Database, Sprout, UserCheck } from "lucide-react";
import { farmerApi, type ApiAssessmentResult, type ApiCropContext, type ApiEvidence, type ApiLand } from "../../services/farmer-api";

const value=(payload:Record<string,unknown>,key:string)=>typeof payload[key]==="string"?String(payload[key]):"Tidak tersedia";
export function FieldSummaryPage(){
  const {landId=""}=useParams(); const [params]=useSearchParams(); const requestedCase=params.get("case");
  const [land,setLand]=useState<ApiLand|null>(null); const [crop,setCrop]=useState<ApiCropContext|null>(null); const [evidence,setEvidence]=useState<ApiEvidence[]>([]); const [result,setResult]=useState<ApiAssessmentResult|null>(null); const [caseId,setCaseId]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{let active=true;(async()=>{try{const [l,c,cases]=await Promise.all([farmerApi.getLand(landId),farmerApi.getActiveCrop(landId).catch(()=>null),farmerApi.listDecisionCases()]); const selected=cases.find(x=>x.id===requestedCase&&x.land_id===landId)||cases.filter(x=>x.land_id===landId).sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0]; if(!selected)throw new Error("Belum ada rembuk untuk lahan ini"); const [ev,assessment]=await Promise.all([farmerApi.listEvidence(selected.id),farmerApi.getAssessment(selected.id)]); if(active){setLand(l);setCrop(c);setCaseId(selected.id);setEvidence(ev);setResult(assessment);}}catch(e){if(active)setError(e instanceof Error?e.message:"Ringkasan gagal dimuat")}})();return()=>{active=false};},[landId,requestedCase]);
  const bmkg=useMemo(()=>evidence.filter(e=>e.type==="bmkg_forecast").sort((a,b)=>b.collected_at.localeCompare(a.collected_at))[0],[evidence]); const field=useMemo(()=>evidence.filter(e=>e.type==="field_pulse").sort((a,b)=>b.collected_at.localeCompare(a.collected_at))[0],[evidence]);
  return <div className="min-h-screen bg-[#f3f3ec] px-4 py-7 text-[#15240a] sm:px-8"><main className="mx-auto max-w-[1000px] space-y-5">
    <Link to={`/farmer/lands/${landId}`} className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/>Kembali ke detail lahan</Link>
    <section><span className="rounded-full bg-white px-3 py-1 text-xs">Ringkasan bukti · bukan keputusan otomatis</span><h1 className="mt-3 font-display text-3xl font-bold">Dasar Pertimbangan {land?.name||"Lahan"}</h1><p className="mt-1 text-sm text-[#44483f]">Sistem menyajikan bukti, keterbatasan, dan opsi. Keputusan akhir tetap milik manusia.</p></section>
    {error?<div className="rounded-2xl bg-[#fff3df] p-5">{error}</div>:!result?<div className="h-64 animate-pulse rounded-2xl bg-white"/>:<>
      <div className="grid gap-4 md:grid-cols-3">
        <article className="rounded-2xl border-t-4 border-[#3b9bc4] bg-white p-5"><CloudSun className="text-[#327ea9]"/><p className="mt-3 text-xs font-bold">BMKG</p><h2 className="mt-1 font-display text-xl font-bold">{bmkg?"Prakiraan resmi tersedia":"Belum tersedia"}</h2><p className="mt-2 text-xs">{bmkg?.source||"Sumber belum tercatat"} · {bmkg?.freshness_status||"kesegaran belum dinilai"}</p><p className="mt-3 text-[10px]">{bmkg?.is_mock?"Data demo/mock":"Non-mock"}</p></article>
        <article className="rounded-2xl border-t-4 border-[#85c254] bg-white p-5"><UserCheck className="text-[#4f8a45]"/><p className="mt-3 text-xs font-bold">FIELD PULSE</p><h2 className="mt-1 font-display text-xl font-bold">Air: {field?value(field.payload,"water_presence"):"—"}</h2><p className="mt-2 text-xs">Irigasi: {field?value(field.payload,"irrigation_flow"):"—"}</p><p className="mt-3 text-[10px]">{field?.observed_at?new Date(field.observed_at).toLocaleString("id-ID"):"Waktu belum tercatat"}</p></article>
        <article className="rounded-2xl border-t-4 border-[#dfaa46] bg-white p-5"><Sprout className="text-[#b98532]"/><p className="mt-3 text-xs font-bold">KONTEKS TANAMAN</p><h2 className="mt-1 font-display text-xl font-bold">{crop?.crop_name||"Belum tersedia"}</h2><p className="mt-2 text-xs">{[crop?.variety_name,crop?.growth_stage].filter(Boolean).join(" · ")||"Konteks belum lengkap"}</p></article>
      </div>
      <section className="rounded-2xl bg-[#213014] p-6 text-white"><div className="flex items-center gap-2 text-[#98cf6a]"><Database size={18}/>Assessment rules-based</div><h2 className="mt-3 font-display text-2xl font-bold">{result.assessment.summary}</h2><p className="mt-2 text-sm">Kekuatan dasar: {result.assessment.basis_strength||"belum dinilai"} · Ruleset: {result.assessment.rule_version||"belum dicatat"}</p>{result.assessment.limitations?.length?<ul className="mt-4 list-disc pl-5 text-sm text-[#deded4]">{result.assessment.limitations.map(x=><li key={x}>{x}</li>)}</ul>:null}</section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-display text-xl font-bold">Opsi untuk Dipertimbangkan</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{result.options.map(o=><article key={o.id} className="rounded-xl bg-[#f3f3ec] p-4"><b>{o.title}</b>{o.description&&<p className="mt-1 text-sm">{o.description}</p>}{o.rationale&&<p className="mt-2 text-xs text-[#56652e]">Dasar: {o.rationale}</p>}</article>)}</div></section>
      <div className="rounded-xl bg-[#d9f59b] p-4 text-xs"><b>Jejak audit:</b> Case #{caseId.slice(0,8).toUpperCase()} · {evidence.length} bukti tertaut. Tidak ada klaim sensor, satelit, debit, atau akurasi yang dibuat tanpa data sumber.</div>
    </>}
  </main></div>;
}
