import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { CircleMarker, MapContainer, TileLayer, useMapEvents } from "react-leaflet";
import { ArrowLeft, Check, Crosshair, MapPin } from "lucide-react";
import "leaflet/dist/leaflet.css";
import { readLandDraft, updateLandDraft } from "../../lib/land-draft";
import { farmerApi } from "../../services/farmer-api";

function Picker({ onPick }: { onPick: (point: [number, number]) => void }) {
  useMapEvents({ click: (event) => onPick([event.latlng.lat, event.latlng.lng]) });
  return null;
}
const locationText = (value: unknown) => typeof value === "string" ? value : "";

export function LocationMapPage() {
  const draft = readLandDraft(); const nav = useNavigate();
  const [position, setPosition] = useState<[number, number]>([draft.latitude ?? -7.926976124, draft.longitude ?? 112.6130137732]);
  const [adm4, setAdm4] = useState(draft.adm4Code || ""); const [verified, setVerified] = useState<Record<string, unknown> | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const useGps = () => navigator.geolocation?.getCurrentPosition(({ coords }) => { setPosition([coords.latitude, coords.longitude]); setVerified(null); }, () => setError("Lokasi perangkat belum dapat dibaca."));
  const verify = async () => { if (!/^\d{2}\.\d{2}\.\d{2}\.\d{4}$/.test(adm4)) { setError("ADM4 harus memakai format 00.00.00.0000."); return; } setBusy(true); setError(""); try { const result = await farmerApi.resolveLocation({ lat: position[0], lon: position[1], adm4 }); setVerified(result.adm4Verification.location); } catch (cause) { setVerified(null); setError(cause instanceof Error ? cause.message : "Lokasi gagal diverifikasi"); } finally { setBusy(false); } };
  const save = () => { if (!verified) { setError("Verifikasi kode ADM4 terlebih dahulu."); return; } updateLandDraft({ latitude: position[0], longitude: position[1], adm4Code: adm4, locationSource: "bmkg_verified", province: locationText(verified.provinsi), regency: locationText(verified.kotkab), district: locationText(verified.kecamatan), village: locationText(verified.desa) }); nav("/farmer/lands/new/details"); };
  return <div className="min-h-screen bg-[#f3f3ec] px-4 py-6 text-[#15240a] sm:px-8"><main className="mx-auto max-w-[1100px] space-y-6"><Link to="/farmer/lands/new" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/>Kembali ke Info Lahan</Link><div><h1 className="font-display text-3xl font-bold">Tentukan Titik Lokasi Petak</h1><p className="mt-2 text-sm text-[#56652e]">Klik titik lahan pada peta, lalu verifikasi kode wilayah ADM4 melalui data resmi BMKG.</p></div><div className="grid gap-6 lg:grid-cols-[380px_1fr]"><section className="space-y-4 rounded-2xl bg-white p-5"><label className="block text-sm font-bold">Kode wilayah BMKG (ADM4)<input aria-label="Kode wilayah BMKG (ADM4)" value={adm4} onChange={(event) => { setAdm4(event.target.value.trim()); setVerified(null); }} placeholder="Contoh: 35.73.05.1001" className="mt-2 h-12 w-full rounded-xl bg-[#f3f3ec] px-4 font-mono font-normal outline-none focus:ring-2 focus:ring-[#85c254]"/></label><div className="rounded-xl bg-[#f3f3ec] p-4 text-sm"><p className="font-bold">Koordinat pilihan</p><p className="mt-1 font-mono">{position[0].toFixed(7)}, {position[1].toFixed(7)}</p></div><button onClick={useGps} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#85c254] px-4 py-3 font-semibold"><Crosshair size={17}/>Gunakan GPS perangkat</button><button disabled={busy} onClick={verify} className="w-full rounded-xl bg-[#213014] px-4 py-3 font-bold text-white disabled:opacity-50">{busy ? "Memverifikasi…" : "Verifikasi dengan BMKG"}</button>{verified && <div className="rounded-xl bg-[#e9fcb5] p-4 text-sm"><p className="flex items-center gap-2 font-bold"><Check size={17}/>ADM4 terverifikasi</p><p className="mt-2">{[verified.desa, verified.kecamatan, verified.kotkab, verified.provinsi].map(locationText).filter(Boolean).join(", ")}</p></div>}{error && <p role="alert" className="rounded-xl bg-[#fff3df] p-3 text-sm">{error}</p>}<button disabled={!verified} onClick={save} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#85c254] px-4 py-3 font-bold disabled:opacity-40"><MapPin size={17}/>Gunakan Lokasi Terverifikasi</button></section><div className="h-[540px] overflow-hidden rounded-2xl shadow-md"><MapContainer center={position} zoom={14} className="h-full w-full"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Picker onPick={(point) => { setPosition(point); setVerified(null); }}/><CircleMarker center={position} radius={10} pathOptions={{ color: "#15240a", fillColor: "#85c254", fillOpacity: 1 }}/></MapContainer></div></div></main></div>;
}
